// packages/react/src/components/BubbleMenu.tsx
import React, { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import {
  BubbleMenuPlugin,
  type BubbleMenuPluginProps,
} from "@tiptap/extension-bubble-menu";
import type { Editor } from "@tiptap/core";

export interface BubbleMenuProps {
  editor: Editor | null;
  className?: string;
  children: React.ReactNode;
  tippyOptions?: BubbleMenuPluginProps["tippyOptions"];
  shouldShow?: BubbleMenuPluginProps["shouldShow"];
  pluginKey?: BubbleMenuPluginProps["pluginKey"];
  updateDelay?: BubbleMenuPluginProps["updateDelay"];
}

export const BubbleMenu: React.FC<BubbleMenuProps> = ({
  editor,
  className = "flex items-center gap-1 bg-popover text-popover-foreground border shadow-md rounded-md p-1",
  children,
  tippyOptions = { duration: 100 },
  shouldShow = null,
  pluginKey = "bubbleMenu",
  updateDelay,
}) => {
  const menuEl = useRef<HTMLDivElement | null>(null);
  const [mounted, setMounted] = useState(false);

  if (!menuEl.current && typeof document !== "undefined") {
    menuEl.current = document.createElement("div");
  }

  useEffect(() => {
    if (!editor || !menuEl.current || editor.isDestroyed) {
      return;
    }

    const element = menuEl.current;
    element.className = className;

    const plugin = BubbleMenuPlugin({
      editor,
      element,
      pluginKey,
      tippyOptions,
      shouldShow,
      updateDelay,
    });

    editor.registerPlugin(plugin);
    setMounted(true);

    return () => {
      setMounted(false);
      editor.unregisterPlugin(pluginKey);
      if (element.parentNode) {
        element.parentNode.removeChild(element);
      }
    };
  }, [editor, className, pluginKey]);

  if (!editor || !menuEl.current || !mounted) {
    return null;
  }

  return createPortal(children, menuEl.current);
};

// packages/svelte/src/BubbleMenu.svelte
<script lang="ts">
  import type { Editor } from "@tiptap/core";
  import { BubbleMenuPlugin } from "@tiptap/extension-bubble-menu";

  interface Props {
    editor?: Editor;
    class?: string;
    pluginKey?: any;
    shouldShow?: ((props: any) => boolean) | null;
    updateDelay?: number;
    tippyOptions?: Record<string, any>;
    children?: import("svelte").Snippet;
  }

  let {
    editor,
    class: className = "flex h-fit w-fit items-center gap-1 rounded-md border border-gray-200 bg-white p-1 shadow-md",
    pluginKey = "bubbleMenu",
    shouldShow = null,
    updateDelay = 250,
    tippyOptions = {},
    children,
  }: Props = $props();

  let menuElement = $state<HTMLElement>();

  $effect(() => {
    if (editor && menuElement) {
      const plugin = BubbleMenuPlugin({
        pluginKey,
        editor,
        element: menuElement,
        tippyOptions: {
          duration: 100,
          appendTo: () => document.body,
          ...tippyOptions,
        },
        shouldShow,
        updateDelay,
      });

      editor.registerPlugin(plugin);

      return () => {
        editor.unregisterPlugin(pluginKey);
      };
    }
  });
</script>

<div bind:this={menuElement} class={className} style="visibility: hidden;">
  {#if children}
    {@render children()}
  {/if}
</div>
